language: node_js
node_js:
  - '0.12'

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  yarn: true
  directories:
  - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh


script:
- gulp collecticons
- gulp

deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
branch: "${DEPLOY_BRANCH}"