language: node_js
node_js:
  - "0.12"

env:
  global:
  - GH_REF=github.com/developmentseed/collecticons.git
  - DEPLOY_BRANCH=master
  - secure: "i1KjLDdFqMwDhwDtd1S8bsuh8OQ6CPNrwLQxitBZ+xBpL4Mn4OpkJHT8XRiMe99fUVyIQm0s8Z3tO1Tb7OEU2uL0xPwCSecktJ5KBDWT570/6X7bL41t+dRQ3Y5BTU/WZsFk8rMqUrnbmO6EC91n/B87NGIkfas9BbQS4luTyTHSMcLVcHVdQ6EnNO0PsLS7adB73Ft1nElxrVrFw2uDlDIGK4Lzd/8mT30U29f1cinb+oVgcRBJolOj8n7Di6J6isHlzpaQY/F29fSR2sFe0SkGf9Tpr/J2bq/RrB61wNVxagB/MBfTyaC+7qUyTkkDFm0ZnivWf5It1DIxZdkaw09OxhpYzCVZJUxp5BGl4NLA2NlOl13oZGOasDURretnwqeWJrqi0fbhPn/qKvjx73M63SYlt9ycvwhjWTmtMpzvVTm7dLz/qm7GGVAuna9QW05jbOB4M/hmgixNl0n6r/cqOB111AVI0+Hfl3lRxHfY5uyGoPzbjzfYCtVkqWd05S4zibxXJWi/s+nxqY7j8EXK7fSisnXhdPQ/W4Jy3xO/CusyFexcEbhuNLY0LlH0VKfWSQB5kzmc65bxsdKTR+gClDfMiud1ZrmXNnp2+KeKVld6aTT1ONTOB8kVmIrjD8fOaQ55ER3Yjb9qOd/381O6o7b9qna4lOmlWF95A9c="

cache:
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh

script:
- gulp collecticons
- gulp

after_success:
- ./.build_scripts/deploy.sh
