name: Publish Package to npmjs
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: enable corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install packages
        run: yarn

      - name: Creat JSX icons from SVG
        run: yarn icons
        
      - name: Build the packages
        run: yarn build --no-private
        
      - name: Publishing to NPM 🚀
        run: yarn publish -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
